version: '3.8'
services:
  redis:
    image: redis:alpine
    ports: ["6379:6379"]
  mongodb:
    image: mongo:6
    ports: ["27017:27017"]
  app:
    build: .
    ports: ["8000:8000"]
    depends_on: [redis, mongodb]
    environment:
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongodb:27017/forex_mas
